# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

app_identifier("com.ttqqcc.rawback")
username(ENV["FASTLANE_APPLE_ID"] || ENV["DELIVER_USERNAME"]) if ENV["FASTLANE_APPLE_ID"] || ENV["DELIVER_USERNAME"]
force(true)
